name: ebank_mobile
description: 企业手机网银

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.430
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^2.0.1
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  english_words: ^3.1.5
  fluttertoast: ^7.1.1
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.1.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  flutter_svprogresshud: ^0.0.6 #加载提示框
  encrypt: ^4.0.0 #AES加解密
  flutter_picker: ^1.1.0 #选择器
  popup_window: ^1.1.1 #顶部弹窗
  contact_picker: ^0.0.2 #获取联系人
  left_scroll_actions: ^1.4.0
  webview_flutter: ^1.0.7
  date_format: ^1.0.8
  url_launcher: ^5.1.2
  flutter_tableview: ^1.0.1
  flutter_easyrefresh: ^2.1.7
  flutter_cupertino_date_picker:
    git:
      url: https://github.com/imshashank/flutter-cupertino-date-picker # Repo
      ref: master # Branch name
  ai_decimal_accuracy:
    git:
      url: https://github.com/pdliuw/ai_decimal_accuracy.git
  image_picker: ^0.6.7+22 #选择相册加拍照

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  json_serializable: ^3.5.0 #json和模型互转

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/ic_launcher.png
    #common
    - images/common/check_btn_common_checked.png
    - images/common/check_btn_common_no_check.png
    #login_image
    - images/login/login_bg_biological.png
    - images/login/login_bg_password.png
    - images/login/login_header_logo.png
    - images/login/login_input_account.png
    - images/login/login_input_password.png

    #tabbar
    - images/tabbar/tabbar_home_normal.png
    - images/tabbar/tabbar_home_select.png
    - images/tabbar/tabbar_approval_normal.png
    - images/tabbar/tabbar_approval_select.png
    - images/tabbar/tabbar_mine_normal.png
    - images/tabbar/tabbar_mine_select.png
    - images/tabbar/tabbar_download.png
    - images/tabbar/tabbar_we_chat.png
    - images/tabbar/tabbar_wechat_moments.png
    - images/tabbar/tabbar_delete.png
    - images/tabbar/tabbar_reset.png

    #home
    #home_nav
    - images/home/navIcon/home_nav_message_has.png
    - images/home/navIcon/home_nav_message.png
    - images/home/navIcon/home_nav_service.png
    - images/home/navIcon/home_nav_phone.png
    - images/home/heaerIcon/home_header_person.png
    #home_header
    - images/home/heaerIcon/home_header_bg.png
    - images/home/heaerIcon/home_header_overview.png
    - images/home/heaerIcon/home_header_payment.png
    #home_listIcon
    - images/home/listIcon/home_list_card_bank.png
    - images/home/listIcon/home_list_deposit_records.png
    - images/home/listIcon/home_list_exchange.png
    - images/home/listIcon/home_list_FOREX.png
    - images/home/listIcon/home_list_loan_apply.png
    - images/home/listIcon/home_list_loan_rate.png
    - images/home/listIcon/home_list_loan_recoeds.png
    - images/home/listIcon/home_list_more_arrow.png
    - images/home/listIcon/home_list_overview.png
    - images/home/listIcon/home_list_partner.png
    - images/home/listIcon/home_list_payments.png
    - images/home/listIcon/home_list_statement.png
    - images/home/listIcon/home_list_time_deposit.png
    - images/home/listIcon/home_list_deposit_rates.png
    - images/home/listIcon/home_list_transfer_appointment.png
    - images/home/listIcon/home_list_transfer_plan.png
    - images/home/listIcon/home_list_transfer_record.png
    - images/home/listIcon/home_list_transfer.png

    #mine 个人中心模块
    - images/mine/aboutUs-bg.png
    - images/mine/aboutUs-bg1.png
    - images/mine/aboutUs-icon1.png
    - images/mine/aboutUs-icon2.png
    - images/mine/aboutUs-icon3.png
    - images/mine/aboutUs-icon4.png
    - images/mine/mine-icon.png
    - images/mine/card_background1.png
    - images/mine/card_background2.png

    #time-depost
    - images/time_depost/time_depost_product.png
    - images/time_depost/time_deposit_contract_succeed.png

    #没有数据的提示图片
    - images/noDataIcon/no_data_card.png
    - images/noDataIcon/no_data_person.png
    - images/noDataIcon/no_data_record.png

    #转账图片
    #转账功能页面图片
    - images/transferIcon/transfer_features_icon/transfer_features_plan.png
    - images/transferIcon/transfer_features_icon/transfer_features_record.png
    - images/transferIcon/transfer_features_icon/transfer_features_timely.png
    - images/transferIcon/transfer_features_icon/transfer_features_timely1.png

    #转账记录页面图片
    - images/transferIcon/transfert_to.png
    - images/transferIcon/transfer_from.png
    - images/transferIcon/transfer_wallet.png
    - images/transferIcon/transfer_bank.png
    - images/transferIcon/transfer_plan.png

    #其他
    - images/transferIcon/transfer_sample_placeholder.png

    - images/transferIcon/transfer_features_icon/transfer_features_scan.png
    - images/transferIcon/transfer_features_icon/transfer_features_acount.png
    #其他
    - images/transferIcon/transfer_sample_placeholder.png
    - images/transferIcon/transfer_bank.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
